[build]
  functions = "netlify/functions"
  command = ""  # ← Esto es lo importante: sin comando, porque no construyes nada

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
