[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch", "openai", "@supabase/supabase-js"]

[functions."webhook"]
  runtime = "nodejs20.x"